### ISSUE TITLE
Feed validator complains

### ISSUE THREAD

**Issue by donkirkby** [pyodide/pyodide-blog#9]
Thanks for starting a blog, I look forward to hearing about what the project is working on.

I tried to follow this blog in my [RSS reader], but it complained that the feed was invalid. My reader uses the [W3C validator], and it's complaining about the image tag. The complaint is:
>This feed does not validate.
>line 10, column 4: Missing image element: title [help]
>
>        </image>
>        ^
>In addition, interoperability with the widest range of feed readers could be improved by implementing the following recommendation.
>line 9, column 107: Image link doesn't match channel link [help]
>
>        ... ge%20for%20opengraph,%20twitter-cards%3E</link>
>                                                     ^

Sorry I can't offer a PR, but I've never used Hugo.

[RSS reader]: https://theoldreader.com/
[W3C validator]: http://validator.w3.org/feed/check.cgi?url=https://blog.pyodide.org/

**Comment by rth** [comment]
Thanks for raising this issue @donkirkby !  I was hoping someone would check RSS since we didn't :)

Looks like one of the config values was not correctly provided: #10 should fix it.
